<section class="c-section other-packs">
    <div class="filter-title">
        <span class="content"><span>VOIR AUSSI</span></span>
        <p>Plus de packs !</p>
    </div>

    <div class="packs-grid">
        <div class="item-pack">
            <div class="row row-0-mobile">
                <div class="col-sm-9">
                    <div class="row row-0-mobile">
                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/xtend-bcaa.jpg" alt="" />
                                </div>
                                <h3>Creatine charged <br> <span>DYMATIZE</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>

                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/products/c4-cellucor-maroc-nutrilionz.jpg" alt="" />
                                </div>
                                <h3>Gold standard Whey <br> <span>MUSCLETECH</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>

                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/products/gold-standard-2.27kg-maroc-nutrilionz.jpg" alt="" />
                                </div>
                                <h3>Gold standard Whey <br> <span>MUSCLETECH</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>

                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/products/shaker.png" alt="" />
                                </div>
                                <h3>Xtend BCAAs <br> <span>Scivation</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-3 last-col d-flex">
                    <div class="infos d-sm-flex align-items-center justify-content-center">
                        <div class="inner">
                            <h2 class="bundle-name"><a href="#">Muscles Builder PACK</a></h2>
                            <div class="pack-counter"><span>(3)</span> articles</div>
                            <div class="rating-box d-none d-sm-block">rating</div>
                            <div class="d-flex d-sm-block align-items-center justify-content-start">
                                <div class="pice-box">
                                    <p class="old-price"><span class="price">399,00 MAD</span></p>
                                    <p class="special-price"><span class="price">310,00 MAD</span></p>
                                </div>
                                <div class="actions">
                                    <a href="#" class="gray-btn" title="Commander"><span><span>En savoir plus</span></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>

        <div class="item-pack">
            <div class="row row-0-mobile">
                <div class="col-sm-9">
                    <div class="row row-0-mobile">
                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/xtend-bcaa.jpg" alt="" />
                                </div>
                                <h3>Creatine charged <br> <span>DYMATIZE</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>

                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/products/c4-cellucor-maroc-nutrilionz.jpg" alt="" />
                                </div>
                                <h3>Gold standard Whey <br> <span>MUSCLETECH</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>

                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/products/gold-standard-2.27kg-maroc-nutrilionz.jpg" alt="" />
                                </div>
                                <h3>Gold standard Whey <br> <span>MUSCLETECH</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>

                        <div class="item col-sm-3">
                            <div class="inner-box d-flex d-sm-block align-items-center">
                                <div class="img-box">
                                    <img width="144" src="images/remove/products/shaker.png" alt="" />
                                </div>
                                <h3>Xtend BCAAs <br> <span>Scivation</span></h3>
                            </div>
                            <div class="plus_icon">+</div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-3 last-col d-flex">
                    <div class="infos d-sm-flex align-items-center justify-content-center">
                        <div class="inner">
                            <h2 class="bundle-name"><a href="#">Clean PACK</a></h2>
                            <div class="pack-counter"><span>(3)</span> articles</div>
                            <div class="rating-box d-none d-sm-block">rating</div>
                            <div class="d-flex d-sm-block align-items-center justify-content-start">
                                <div class="pice-box">
                                    <p class="old-price"><span class="price">1090,00 MAD</span></p>
                                    <p class="special-price"><span class="price">1008,00 MAD</span></p>
                                </div>
                                <div class="actions">
                                    <a href="#" class="gray-btn" title="Commander"><span><span>En savoir plus</span></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</section>